name: Fix and Build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Fix Missing SDK Path
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
      - name: Build Debug APK
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: game-apk
          path: "**/*.apk"
